// <auto-generated />
using System;
using FetchTheWeather.Backend.Service.Weather.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FetchTheWeather.Backend.Service.Weather.Migrations
{
    [DbContext(typeof(WeatherDataContext))]
    [Migration("20251126131020_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FetchTheWeather.Backend.Service.Weather.Models.Domain.WeatherData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AirPressureHpa")
                        .HasColumnType("real");

                    b.Property<float>("AirQualityPpm")
                        .HasColumnType("real");

                    b.Property<float>("HumidityPercent")
                        .HasColumnType("real");

                    b.Property<bool>("IsRaining")
                        .HasColumnType("boolean");

                    b.Property<float>("RainfallMm")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureCelsius")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeatherStationId")
                        .HasColumnType("uuid");

                    b.Property<float>("WindSpeedKph")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("FetchTheWeather.Backend.Service.Weather.Models.Domain.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");
                });
#pragma warning restore 612, 618
        }
    }
}
