// <auto-generated />
using System;
using FetchTheWeather.Backend.Service.Weather.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FetchTheWeather.Backend.Service.Weather.Migrations
{
    [DbContext(typeof(WeatherDataContext))]
    [Migration("20251124140345_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FetchTheWeather.Backend.Service.Weather.Models.Domain.WeatherData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AirPressureHpa")
                        .HasColumnType("real");

                    b.Property<float>("HumidityPercent")
                        .HasColumnType("real");

                    b.Property<bool>("IsRaining")
                        .HasColumnType("boolean");

                    b.Property<float>("RainfallMm")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureCelsius")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeatherStationId")
                        .HasColumnType("uuid");

                    b.Property<float>("WindSpeedKph")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbd52613-e281-435d-9f3c-b208a1f68ee3"),
                            AirPressureHpa = 200f,
                            HumidityPercent = 40f,
                            IsRaining = false,
                            RainfallMm = 0f,
                            TemperatureCelsius = 275f,
                            Timestamp = new DateTime(1979, 7, 28, 22, 35, 5, 0, DateTimeKind.Utc),
                            WeatherStationId = new Guid("5a44cc62-4add-4e5c-896d-a2333b18af92"),
                            WindSpeedKph = 120f
                        },
                        new
                        {
                            Id = new Guid("94076bcd-04b9-412b-83af-d83c99e5b841"),
                            AirPressureHpa = 200f,
                            HumidityPercent = 50f,
                            IsRaining = false,
                            RainfallMm = 0f,
                            TemperatureCelsius = 260f,
                            Timestamp = new DateTime(1979, 7, 28, 23, 35, 5, 0, DateTimeKind.Utc),
                            WeatherStationId = new Guid("5a44cc62-4add-4e5c-896d-a2333b18af92"),
                            WindSpeedKph = 120f
                        },
                        new
                        {
                            Id = new Guid("445f6cee-fd64-4693-b8ab-cf6cd21aa35c"),
                            AirPressureHpa = 40f,
                            HumidityPercent = 40f,
                            IsRaining = true,
                            RainfallMm = 50f,
                            TemperatureCelsius = 200f,
                            Timestamp = new DateTime(1979, 7, 29, 0, 35, 5, 0, DateTimeKind.Utc),
                            WeatherStationId = new Guid("5a44cc62-4add-4e5c-896d-a2333b18af92"),
                            WindSpeedKph = 60f
                        },
                        new
                        {
                            Id = new Guid("9105ff38-cb7d-4469-8eb7-0d5252277a90"),
                            AirPressureHpa = 220f,
                            HumidityPercent = 60f,
                            IsRaining = true,
                            RainfallMm = 20f,
                            TemperatureCelsius = 250f,
                            Timestamp = new DateTime(1979, 7, 30, 22, 35, 5, 0, DateTimeKind.Utc),
                            WeatherStationId = new Guid("5a44cc62-4add-4e5c-896d-a2333b18af92"),
                            WindSpeedKph = 100f
                        });
                });

            modelBuilder.Entity("FetchTheWeather.Backend.Service.Weather.Models.Domain.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a44cc62-4add-4e5c-896d-a2333b18af92"),
                            Location = "Weather Station",
                            Name = "Weather Station"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
